### ISSUE TITLE
Keepalived version is inconsistent

### ISSUE THREAD

**Issue by obazoud** [chef-cookbooks/keepalived#18]
Hi folks,

Keepalived cookbook version is inconsistent with master branch, 1.2 git tag supermarket.

* lastest version in supermarket is [1.2.0](https://supermarket.getchef.com/cookbooks/keepalived)
* lastest git tag is [v1.2.0](https://github.com/opscode-cookbooks/keepalived/tree/v1.2.0) and contains [Version bump to 1.2.0 - d44df3b](https://github.com/opscode-cookbooks/keepalived/commit/d44df3bad705eb6c717a937b59740ab3a88ea936) that changes version from 1.1.1 to 1.2.0. It contains [Publish 1.2.0 Changelog - c2eec22](https://github.com/opscode-cookbooks/keepalived/commit/c2eec2217e019ce39cdf2ef28fb3718600a63)
* lastest metadata on master is [v1.1.1](https://github.com/opscode-cookbooks/keepalived/blob/e3e8f8052899ec8b6b3443b3c55afa8a0c5b9427/metadata.rb#L7) @ master and does not contain d44df3bad705eb6c717a937b59740ab3a88ea936 neither c2eec2217e019ce39cdf2ef28fb3718600a6339f

I am totally lost...
do I miss something ? or someone has forgotten to push git commits ?

**Comment by nathwill** [comment]
oof, that does sound confusing, sorry about that. at this point, 1.3.0 has been out for a while, and 2.0 is imminent, so i'm assuming this isn't an issue anymore, and that if it is, the solution will be to upgrade, so closing this issue.
