### ISSUE TITLE
Instances don't support have a notify_script set

### ISSUE THREAD

**Issue by LiamHaworth** [chef-cookbooks/keepalived#25]
When defining a instance in overrides, most required settings can be set except `notify_script`, for some users this is a requirement.

A instance can have only one `notify_script` set and would be set like so, `keepalived['instances']['instance_name']['notify_script'] = '/etc/keepalived/notify.sh'` (This is just an example, other users may have it sent to something else)

**Comment by nathwill** [comment]
this is supported in latest code on master, expect to see v2 hit supermarket soon!
