### ISSUE TITLE
Need support for more keepalived keywords

### ISSUE THREAD

**Issue by nimeshsubramanian** [chef-cookbooks/keepalived#31]
Need support for the following keepalived keywords
```
* garp_master_repeat 
* garp_master_refresh 
* garp_master_refresh_repeat
* smtp_alert
* notify_master
* notify_backup
* notify_fault 
* garp_master_delay
* fall a check_script keyword
* rise a check_script keyword
```

**Comment by nimeshsubramanian** [comment]
submitted a patch https://github.com/chef-cookbooks/keepalived/pull/30

**Comment by nathwill** [comment]
so some variation of these appears to be supported now, though `garp_master_repeat`, `garp_master_refresh`, and `garp_master_refresh_repeat` seem to have been prefixed with `vrrp_` upstream; do you have a specific need for those `garp_master_*` keywords in their older form?

**Comment by nathwill** [comment]
woops, didn't mean to close this.
