### ISSUE TITLE
Please release the new code: v.1.3.0 is missing the notify script settings

### ISSUE THREAD

**Issue by LuigiClemente-Awin** [chef-cookbooks/keepalived#32]
I need the full set of keepalive configuration attributes you have in your development code:

:smtp_alert => true # Enables SMTP notifications
:notify_master => nil # Script to be run on transition to MASTER state
:notify_backup => nil # Script to be run on transition to BACKUP state
:notify_fault => nil # Script to be run when check_script fails

Do you now when the new version will be released?

**Comment by uzyexe** [comment]
+1

**Comment by nathwill** [comment]
@LuigiClemente-Awin @uzyexe i'm going to work on polishing the documentation and doing the last bit of prep to get 2.0 out the door, so expect to see improved support for these keywords in the next week or two at most.
