### ISSUE TITLE
keepalived_vrrp_instance config file parameter order causes keepalived failure

### ISSUE THREAD

**Issue by banks** [chef-cookbooks/keepalived#43]
### Cookbook version
2.0.0

### Chef-client version
12.11.18

### Platform Details
Ubuntu 14.04; AWS

### Scenario:
Configure VRRP Instance with unicast peer. Per https://blog.logentries.com/2014/12/keepalived-and-haproxy-in-aws-an-exploratory-guide/

### Steps to Reproduce:
Add VRRP instance config like:

```
  keepalived_vrrp_instance 'test' do
    virtual_router_id 42
    # Making both backup and adding `nopreempt` is a trick that prevent the master taking over the IP once it comes back
    # this is desirable in our case as it likely has a blip of lost data that the backup doesn't
    state 'BACKUP'
    nopreempt true
    interface eth0
    priority 100
    authentication auth_type: 'PASS', auth_pass: 'foo'
    unicast_src_ip '10.0.0.1'
    unicast_peer ['10.0.0.2']
    notify_master "/usr/local/bin/failover.sh"
  end
```

### Expected Result:
Working VRRP instance

### Actual Result:
The config file is rendered in some "random" order (i.e. however ruby hash ordered the keys I suspect)

But it seems like keepalived requires `virtual_router_id` to be before `unicast_peers`.

For me the file is rendered as:

```
vrrp_instance test {
        notify_master /usr/local/bin/failover.sh
        state BACKUP
        interface eth0
        unicast_src_ip 10.0.0.1
        unicast_peer {
                10.0.0.2
                }
        virtual_router_id 42
        priority 100
        authentication {
                auth_type PASS
                auth_pass foo
                }
        nopreempt
        }

```

Which results in VRRP crashing on load and respawning in a tight loop with:

```
Starting VRRP child process, pid=8932
Interface queue is empty
Netlink reflector reports IP 10.0.0.1 added
Netlink reflector reports IP fe80::c40:55ff:fe84:4cc3 added
Registering Kernel netlink reflector
Registering Kernel netlink command channel
Registering gratuitous ARP shared channel
Initializing ipvs 2.6
Opening file '/etc/keepalived/keepalived.conf'.
Opening file '/etc/keepalived/conf.d/keepalived_vrrp_instance__test__.conf'.
VRRP_Instance(prometheus) the virtual id must be set!
VRRP child process(8932) died: Respawning
[repeat]
```

That was from running it in foreground with `keepalived -n -l -D -f /etc/keepalived/keepalived.conf`

If I move the `virtual_router_id` line up anywhere _before_ the `unicast_peer` one, keepalived starts successfully:

```
$keepalived -n -l -D -f /etc/keepalived/keepalived.conf
Starting Healthcheck child process, pid=9280
Initializing ipvs 2.6
Starting VRRP child process, pid=9281
Interface queue is empty
Netlink reflector reports IP 10.0.0.1 added
Netlink reflector reports IP fe80::c40:55ff:fe84:4cc3 added
Registering Kernel netlink reflector
Registering Kernel netlink command channel
Interface queue is empty
Netlink reflector reports IP 10.0.0.1 added
Opening file '/etc/keepalived/keepalived.conf'.
Netlink reflector reports IP fe80::c40:55ff:fe84:4cc3 added
Registering Kernel netlink reflector
Registering Kernel netlink command channel
Opening file '/etc/keepalived/conf.d/keepalived_vrrp_instance__test__.conf'.
Registering gratuitous ARP shared channel
Initializing ipvs 2.6
Configuration is using : 5821 Bytes
Using LinkWatch kernel netlink reflector...
Opening file '/etc/keepalived/keepalived.conf'.
Opening file '/etc/keepalived/conf.d/keepalived_vrrp_instance__test__.conf'.
Configuration is using : 59592 Bytes
Using LinkWatch kernel netlink reflector...
VRRP_Instance(test) Entering BACKUP STATE
VRRP sockpool: [ifindex(2), proto(112), fd(10,11)]
VRRP_Instance(test) Transition to MASTER STATE
VRRP_Instance(test) Entering MASTER STATE
Opening script file /usr/local/bin/failover.sh
```

I'm not sure why keepalived seems so sensitive to ordering in the config files nor which other possible parameters might cause a similar issue.

For now It means I have to bypass the `keepalived_vrrp_instance` entirely and write my config file explicitly...

**Comment by nathwill** [comment]
thanks for the bug report @banks, that's weird indeed. do you want to PR a fix for it, or shall i dive in and tackle it (i assume re-ordering the hash unicast_peer entry in the params hash should do it)?

**Comment by nathwill** [comment]
have a fix in the works, just working out some unrelated tweaks now.

**Comment by nathwill** [comment]
@banks this is out in v2.1.0, can you test and confirm this fixes it for you?

**Comment by banks** [comment]
Thanks for getting on this so fast! 

Sorry for not replying earlier. I filed this right before I stopped work and went to bed!

I'll report back by EOD when I've had a chance to test.

**Comment by banks** [comment]
Yep that has fixed the issue for me. Thanks!

**Comment by nathwill** [comment]
glad to hear, it, thanks for checking!
