### ISSUE TITLE
Incompatibility with Chef 13

### ISSUE THREAD

**Issue by tas50** [chef-cookbooks/keepalived#53]
The keepalived_vrrp_instance resource has a property named "state" which is the name of a internal method on the resource class in Chef. As of Chef 13 we're no longer allowing the reuse of these names so this will fail. We'll need to rename this to something not used internally.

**Comment by tas50** [comment]
Chef::Exceptions::DeprecatedFeatureError
----------------------------------------
"Property `state` of resource `keepalived_vrrp_instance` overwrites an existing method. Please use a different property name. This will raise an exception in Chef 13. (CHEF-11)/opt/kitchen/cache/cookbooks/keepalived/libraries/resources.rb:33:in `block in option_properties'.\nPlease see https://docs.chef.io/deprecations_property_name_collision.html for further details and information on how to correct this problem. at /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.37/lib/chef/formatters/doc.rb:419:in `deprecation'"

**Comment by nathwill** [comment]
ack, thanks @tas50; i'll get it fixed up.

**Comment by tas50** [comment]
I should have mentioned this is tracked here https://docs.google.com/a/opscode.com/spreadsheets/d/1AB49oQBExuCTV0HOcMurf0dfHMYUoXnALNoUhkEO6LM/edit?usp=sharing

**Comment by nathwill** [comment]
@tas50 looks like a private document, so i'll take your word for it. i'll give a shout when the PR is ready so any tracking updates can be made as appropriate.
