### ISSUE TITLE
keepalived_vrrp_instance authentication doesn't accept hash

### ISSUE THREAD

**Issue by mengesb** [chef-cookbooks/keepalived#57]
### Cookbook version
3.1.0

### Chef-client version
12.19.36

### Platform Details
centos 6

### Scenario:
pass to `keepalived_vrrp_instance` attribute `authentication` as hash

### Steps to Reproduce:
1. Call `keepalived_vrrp_instance` with attribute `authentication` set to hash
2. Run chef

### Expected Result:
Chef client run completed successfully

### Actual Result:
```
Chef::Exceptions::ValidationFailed
----------------------------------
Option authentication's value {"auth_type"=>"PASS", "auth_pass"=>"passwd"} has required configuration!
```

### More information:
Example vrrp_config hash:
```ruby
default['kad']['vrrp_config'] = {
  authentication: {
    auth_type: 'PASS',
    auth_pass: 'passwd',
  },
}
```

Calling `keepalived_vrrp_instance` with data structure
```ruby
keepalived_vrrp_instance 'test' do
  authentication node['kad']['vrrp_config']['authentication']
  interface node['network']['default_interface']
  virtual_router_id 50
  priority 100
  advert_int 1
  virtual_ipaddress ['192.168.1.110']
end
```

Suspected to be here: https://github.com/chef-cookbooks/keepalived/blob/3a0c323e843e678fde1ce8767413da85b291562c/libraries/keepalived.rb#L129-L131

**Comment by nathwill** [comment]
i believe attributes are actually a `Mash`?, try running `#to_h` on the attribute.

**Comment by nathwill** [comment]
ok, it is a `Chef::Node::ImmutableMash`, but that's not the problem; it seems the problem is that the hash being passed in is not preserving symbols as the keys that are being checked for in the callback.

the below works:

```ruby
keepalived_vrrp_instance 'test' do
  authentication({
    auth_type: node['kad']['vrrp_config']['authentication']['auth_type'],
    auth_pass: node['kad']['vrrp_config']['authentication']['auth_pass']
  }) 
  interface node['network']['default_interface']
  virtual_router_id 50
  priority 100
  advert_int 1
  virtual_ipaddress ['192.168.1.110']
end
```
